[project]
name = "pythonforcyber"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dnspython>=2.7.0",
    "paramiko>=3.5.1",
    "pyinstaller>=6.12.0",
    "scapy>=2.6.1",
]
